### ISSUE TITLE
Add unique projects completed by students into the website.

### ISSUE THREAD

**Issue by sarwar-jahin-port** [naimulcsx/progHours#189]
Every semester as we students are building lots of projects. In my experience lots of projects out there which are really amazing but no use after project submission.
What if there is a page where all top projects will be listed. People can come and see those amazing projects, their resources, video presentation and get inspired.
Student will come and submit there project. Authority will check and verify.

**Comment by Imtiaz246** [comment]
Good Idea. But it's not relevant to the core domain of this project. You can build a whole new project for this.
